In [39]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [40]:
from google.colab import files

In [41]:
uploaded = files.upload()

Saving cancer.csv to cancer.csv

In [42]:
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

User uploaded file "cancer.csv" with length 125204 bytes

In [43]:
import io

In [44]:
cancer = pd.read_csv(io.StringIO(uploaded['cancer.csv'].decode('utf-8')))

In [45]:
cancer.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [46]:
cancer.describe()

                 id  radius_mean  ...  fractal_dimension_worst  Unnamed: 32
count  5.690000e+02   569.000000  ...               569.000000          0.0
mean   3.037183e+07    14.127292  ...                 0.083946          NaN
std    1.250206e+08     3.524049  ...                 0.018061          NaN
min    8.670000e+03     6.981000  ...                 0.055040          NaN
25%    8.692180e+05    11.700000  ...                 0.071460          NaN
50%    9.060240e+05    13.370000  ...                 0.080040          NaN
75%    8.813129e+06    15.780000  ...                 0.092080          NaN
max    9.113205e+08    28.110000  ...                 0.207500          NaN

[8 rows x 32 columns]

In [49]:
#Separating feature columns from label
feature_cols = ['radius_mean', 'texture_mean', 'perimeter_mean', 
                'area_mean','smoothness_mean','compactness_mean','concavity_mean',
                'concave points_mean','symmetry_mean','fractal_dimension_mean','radius_se',
                'texture_se','perimeter_se','area_se','smoothness_se','compactness_se',
                'concavity_se', 'concave points_se', 'symmetry_se', 'fractal_dimension_se', 
                'radius_worst', 'texture_worst', 'perimeter_worst', 'area_worst', 'smoothness_worst', 
                'compactness_worst', 'concavity_worst', 'concave points_worst', 'symmetry_worst',
                'fractal_dimension_worst']
X = cancer[feature_cols]
y = cancer.diagnosis

In [50]:
#Splitting data for testing and training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [55]:
#KNN model for training data and accuracy on testing data for neighbors ranging from 2-10
for i in range(2,10):
  knn = KNeighborsClassifier(n_neighbors=i)
  knn = knn.fit(X_train,y_train)
  y_test_pred = knn.predict(X_test)
  y_train_pred = knn.predict(X_train)
  print("Accuracy for ", i, "neighbors: ",knn.score(X_test,y_test))

print("\nWe get highest accuracy for k = 7 neighbors at 93.56%")

Accuracy for  2 neighbors:  0.8947368421052632
Accuracy for  3 neighbors:  0.9239766081871345
Accuracy for  4 neighbors:  0.9298245614035088
Accuracy for  5 neighbors:  0.9298245614035088
Accuracy for  6 neighbors:  0.9239766081871345
Accuracy for  7 neighbors:  0.935672514619883
Accuracy for  8 neighbors:  0.9298245614035088
Accuracy for  9 neighbors:  0.9298245614035088

We get highest accuracy for k = 7 neighbors at 93.56%